window.KAIDA_CONFIG = {
  API_URL: "PASTE_YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE",
  FINANCE_WHATSAPP: "", // digits only, e.g. 13015551234
  ORGANIZATION_NAME: "Kailahun Descendants Association USA",
  SHORT_NAME: "KAIDA-USA",
  REGISTRATION_FEE: 50,
  MONTHLY_DUES: 10,
  CURRENCY: "USD"
};
